name: http_hive_cache
description: Simplified caching of HTTP GET requests. Hive is used for data storage.
version: 1.0.1
homepage: https://github.com/koji-1009/http_hive_cache

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.0.0
  hive_ce: ^2.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dapper: ^1.4.0
